import type { ThinkingLevel } from "../dsl/types.ts";
import { contentHash } from "../shared/json.ts";
export interface AvailableModel { provider: string; id: string; name?: string; reasoning?: boolean; thinkingLevelMap?: Partial<Record<ThinkingLevel, string | null>>; input?: string[]; contextWindow?: number; maxTokens?: number; cost?: { input?: number; output?: number; cacheRead?: number; cacheWrite?: number } }
export interface RouteRequest { taskClass: "router" | "generation" | "scout" | "implementation" | "review" | "synthesis" | "repair" | "gate"; prompt: string; expectedContext?: number; needsImages?: boolean; writer?: boolean; priorModel?: string; risk?: "low" | "medium" | "high" }
export interface ModelDecision { model: string; thinking: ThinkingLevel; fallbackModels: string[]; confidence: number; reasons: string[]; expectedStrengths: string[]; escalationTriggers: string[]; source: "deterministic" | "llm"; cacheKey: string }
export type RouteModelCall = (request: RouteRequest, catalog: AvailableModel[]) => Promise<unknown>;
const LEVELS: ThinkingLevel[] = ["off", "minimal", "low", "medium", "high", "xhigh", "max"];
export class ModelRouter {
  private cache = new Map<string, ModelDecision>();
  constructor(private models: AvailableModel[], private call?: RouteModelCall) {}
  async route(request: RouteRequest): Promise<ModelDecision> {
    const catalog = this.eligible(request); if (!catalog.length) throw new Error("No authenticated model satisfies campaign requirements."); const cacheKey = contentHash({ request: { ...request, prompt: contentHash(request.prompt) }, catalog }); const cached = this.cache.get(cacheKey); if (cached) return structuredClone(cached);
    if (this.call) { try { const raw = await this.call(request, catalog); const decision = this.validate(raw, request, catalog, cacheKey); if (decision) { this.cache.set(cacheKey, decision); return structuredClone(decision); } } catch { /* deterministic fallback */ } }
    const ranked = [...catalog].sort((a, b) => score(a, request) - score(b, request) || key(a).localeCompare(key(b))); const selected = ranked[0]!; const desired: ThinkingLevel = request.risk === "high" || request.taskClass === "review" ? "high" : request.taskClass === "implementation" || request.taskClass === "generation" ? "medium" : "low"; const thinking = clampThinking(selected, desired);
    const decision: ModelDecision = { model: key(selected), thinking, fallbackModels: ranked.slice(1, 4).map(key), confidence: knownConfidence(selected), reasons: [`Deterministic capability profile selected rank 1/${ranked.length}.`, `Task class=${request.taskClass}; risk=${request.risk ?? "medium"}.`], expectedStrengths: strengths(selected, request), escalationTriggers: ["model unavailable", "invalid structured output twice", "gate capability failure", "no-progress hash repeated", "context estimate exceeded"], source: "deterministic", cacheKey }; this.cache.set(cacheKey, decision); return structuredClone(decision);
  }
  routeSync(request: RouteRequest): ModelDecision { const catalog = this.eligible(request); if (!catalog.length) throw new Error("No authenticated model satisfies campaign requirements."); const ranked = [...catalog].sort((a, b) => score(a, request) - score(b, request) || key(a).localeCompare(key(b))); const selected = ranked[0]!; const cacheKey = contentHash({ request: { ...request, prompt: contentHash(request.prompt) }, catalog }); return { model: key(selected), thinking: clampThinking(selected, request.taskClass === "implementation" ? "medium" : "low"), fallbackModels: ranked.slice(1, 4).map(key), confidence: knownConfidence(selected), reasons: ["Deterministic offline route."], expectedStrengths: strengths(selected, request), escalationTriggers: ["model unavailable", "gate failure", "no progress"], source: "deterministic", cacheKey }; }
  private eligible(request: RouteRequest): AvailableModel[] { return this.models.filter((model) => (!request.needsImages || model.input?.includes("image")) && (!request.expectedContext || (model.contextWindow ?? 0) >= request.expectedContext)); }
  private validate(raw: unknown, request: RouteRequest, catalog: AvailableModel[], cacheKey: string): ModelDecision | undefined { if (!raw || typeof raw !== "object") return; const value = raw as Record<string, unknown>; const model = catalog.find((item) => key(item) === value.model); if (!model || typeof value.thinking !== "string" || !LEVELS.includes(value.thinking as ThinkingLevel)) return; const fallbacks = Array.isArray(value.fallbackModels) ? value.fallbackModels.filter((item): item is string => typeof item === "string" && catalog.some((model) => key(model) === item) && item !== value.model) : []; return { model: key(model), thinking: clampThinking(model, value.thinking as ThinkingLevel), fallbackModels: fallbacks, confidence: clamp(Number(value.confidence ?? 0.5), 0, 1), reasons: stringList(value.reasons), expectedStrengths: stringList(value.expectedStrengths), escalationTriggers: stringList(value.escalationTriggers), source: "llm", cacheKey }; }
}
function key(model: AvailableModel): string { return `${model.provider}/${model.id}`; }
function score(model: AvailableModel, request: RouteRequest): number { const id = `${model.name ?? ""} ${model.id}`.toLowerCase(); const cost = (model.cost?.input ?? 0) + (model.cost?.output ?? 0) * 2; let capability = 50; if (/haiku|mini|small|flash|20b|lite/.test(id)) capability = 10; if (/sonnet|medium|pro/.test(id)) capability = 30; if (/opus|max|ultra/.test(id)) capability = 60; const required = request.taskClass === "router" || request.taskClass === "scout" ? 10 : request.taskClass === "implementation" || request.taskClass === "generation" ? 30 : request.taskClass === "review" && request.risk === "high" ? 55 : 30; const underpowered = capability < required ? (required - capability) * 100 : 0; return underpowered + capability + cost; }
function clampThinking(model: AvailableModel, desired: ThinkingLevel): ThinkingLevel { if (!model.reasoning) return "off"; const map = model.thinkingLevelMap; const desiredIndex = LEVELS.indexOf(desired); for (let distance = 0; distance < LEVELS.length; distance++) { for (const index of [desiredIndex - distance, desiredIndex + distance]) { const level = LEVELS[index]; if (!level) continue; if (map?.[level] !== null && (level !== "xhigh" && level !== "max" || map?.[level] !== undefined)) return level; } } return "off"; }
function knownConfidence(model: AvailableModel): number { return /haiku|mini|small|flash|sonnet|opus|gpt|claude|gemini|qwen|deepseek/.test(model.id.toLowerCase()) ? 0.8 : 0.45; }
function strengths(model: AvailableModel, request: RouteRequest): string[] { return [model.reasoning ? "reasoning" : "fast text generation", request.needsImages ? "image input" : "text input", `${model.contextWindow ?? "unknown"} context window`]; }
function clamp(value: number, min: number, max: number): number { return Math.min(max, Math.max(min, Number.isFinite(value) ? value : min)); }
function stringList(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
